import java.math.BigInteger;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
	public static void main(String[] args) {
		if (args.length == 1) {
			BigInteger number = new BigInteger(args[0]);
			System.out.println("Input: " + number);
			System.out.println("Output: " + NumberUtils.toEnglish(number));
		} else {
			System.out.println("You must pass a number");
		}
	}
}
