/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
import spock.lang.Specification

class NumberUtilsTest extends Specification {
	def "basic numbers to english"() {
		expect:
		NumberUtils.toEnglish(number) == english

		where:
		number | english
		0      | "zero"
		1      | "one"
		2      | "two"
		3      | "three"
		4      | "four"
		5      | "five"
		6      | "six"
		7      | "seven"
		8      | "eight"
		9      | "nine"
		10     | "ten"
		11     | "eleven"
		12     | "twelve"
		13     | "thirteen"
		14     | "fourteen"
		15     | "fifteen"
		16     | "sixteen"
		17     | "seventeen"
		18     | "eighteen"
		19     | "nineteen"
	}

	def "tens to english"() {
		expect:
		NumberUtils.toEnglish(number) == english

		where:
		number | english
		20     | "twenty"
		30     | "thirty"
		40     | "forty"
		50     | "fifty"
		60     | "sixty"
		70     | "seventy"
		80     | "eighty"
		90     | "ninety"
	}

	def "tens combined with basic to english"() {
		expect:
		NumberUtils.toEnglish(number) == english

		where:
		number | english
		21     | "twenty-one"
		29     | "twenty-nine"
		99     | "ninety-nine"
	}
}
